### ISSUE TITLE
[API] generate_qa_docs in trial_tasks.py

### ISSUE THREAD

**Issue by hongsw** [Marker-Inc-Korea/AutoRAG#1004]
generate_qa_docs in trial_tasks.py

_Originally posted by @hongsw in https://github.com/Marker-Inc-Korea/AutoRAG/issues/987#issuecomment-2497547394_

**Comment by hongsw** [comment]
![Image](https://github.com/user-attachments/assets/d1da4a9f-7b0d-4727-afa1-afe502ec0999)

**Comment by vkehfdl1** [comment]
close at #1005
