### ISSUE TITLE
[Feature Request] Create multiple questions

### ISSUE THREAD

**Issue by e7217** [Marker-Inc-Korea/AutoRAG#1006]
**Is your feature request related to a problem? Please describe.**
I find the QA generation feature very useful and am eager to make full use of it. I have a question I'd like to ask.

Currently, it seems that only one question is generated per row in the corpus. Is there a feature that allows multiple questions to be generated for a single row? I couldn’t find this feature in the official documentation, so if I’ve missed something, I would appreciate your guidance.

Thank you for developing such a great library!

**Comment by vkehfdl1** [comment]
https://github.com/Marker-Inc-Korea/AutoRAG/pull/1009#issuecomment-2503759822
