### ISSUE TITLE
[Feature Request] It seems that the validation logic is not only performing validation.

### ISSUE THREAD

**Issue by e7217** [Marker-Inc-Korea/AutoRAG#1013]
**Is your feature request related to a problem? Please describe.**
When running AutoRAG, I expected the evaluation logic to be triggered once, but it seems to occur twice. 
![Image](https://github.com/user-attachments/assets/5aa2461b-8ead-4811-a823-5fb960ab5207)
The code related to this is in the validate function of the Validator class.
```python
# start Evaluate at temp project directory
with (
	tempfile.NamedTemporaryFile(suffix=".parquet", delete=False) as qa_path,
	tempfile.NamedTemporaryFile(suffix=".parquet", delete=False) as corpus_path,
	tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as temp_project_dir,
):
	sample_qa_df.to_parquet(qa_path.name, index=False)
	sample_corpus_df.to_parquet(corpus_path.name, index=False)

	evaluator = Evaluator(
		qa_data_path=qa_path.name,
		corpus_data_path=corpus_path.name,
		project_dir=temp_project_dir,
	)
	evaluator.start_trial(yaml_path, skip_validation=True)
	qa_path.close()
	corpus_path.close()
	os.unlink(qa_path.name)
	os.unlink(corpus_path.name)
```

Calling the evaluation twice results in two API requests, causing the user to be charged twice. 
How about performing the validation only for the form?

**Comment by vkehfdl1** [comment]
@e7217 
When we execute validation, we slice the data to the small pieces. Just 5 QAs. So it does not call many APIs. But, still loading and experimenting all features so can check the system quite well.
So it is intended feature.
