### ISSUE TITLE
[Suggestion] How about adding AutoRAG to the LLM Evaluation section of Awesome-LLM?

### ISSUE THREAD

**Issue by e7217** [Marker-Inc-Korea/AutoRAG#1035]
https://github.com/Hannibal046/Awesome-LLM

**Comment by vkehfdl1** [comment]
https://github.com/Hannibal046/Awesome-LLM/pull/186
I made an PR for it!!! 
@e7217

**Comment by vkehfdl1** [comment]
@e7217 AutoRAG is now in the Awesome-LLM
Thanks for your suggestion!!
