### ISSUE TITLE
[BUG] Unexpected keyword argument 'embedding_model' for passage filter module

### ISSUE THREAD

**Issue by rjwharry** [Marker-Inc-Korea/AutoRAG#1042]
**Describe the bug**
unexpected keyword argument 'embedding_model' error occurred in passage filter module such as `SimilarityThresholdCutoff._pure()`

**To Reproduce**
1. set `embedding_model` of `similarity_threshold_cutoff` in config.yaml
2. Run autorag

**Expected behavior**
Succeed

**Full Error log**
TypeError: SimilarityThresholdCutoff._pure() got an unexpected keyword argument 'embedding_model'

**Code that bug is happened**
After init `cls` instance, `embedding_model` key must be popped from `kwargs`. But `kwargs` in `BaseModule` and `SimilarityThresholdCutoff` have different id like deep copy.
```python
class BaseModule(metaclass=ABCMeta):
    @classmethod
        def run_evaluator(
            cls,
            project_dir: Union[str, Path],
            previous_result: pd.DataFrame,
            *args,
            **kwargs,
        ):
            instance = cls(project_dir, *args, **kwargs)
            result = instance.pure(previous_result, *args, **kwargs)
            del instance
            return result
class SimilarityThresholdCutoff(BasePassageFilter):
    def __init__(self, project_dir: str, *args, **kwargs):
        super().__init__(project_dir, *args, **kwargs)
        embedding_model_str = kwargs.pop("embedding_model", "openai")
        self.embedding_model = embedding_models[embedding_model_str]()
```

**Comment by rjwharry** [comment]
I'm figuring out how to pass kwargs as shallow copy

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the SimilarityThresholdCutoff class to handle the 'embedding_model' parameter correctly and prevent it from being passed to the _pure method. Also update the BaseModule class to remove handled arguments before calling the pure method.

You can review changes in this commit: https://github.com/mnmnk43434/Marker-Inc-Korea-AutoRAG-1042/commit/6c9f3e2777d46a10d5a60bf5be52bc624e5dcb3c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by rjwharry** [comment]
Yeah, I agree your approach.
But how about moving `kwargs.pop(args, None)` to `SimilarityThresholdCutoff` class. Because various module classes are inheriting `BaseModule` class and it can cause side effect to other module.
