### ISSUE TITLE
Add n-gram metric options

### ISSUE THREAD

**Issue by Eastsidegunn** [Marker-Inc-Korea/AutoRAG#44]
From PR #40 

I think these n-gram based metrics can open some options.
- N : int  minimum unit for n-gram
- tokenizer : select tokenizer. (according to language, method etc include in tokenizer, tokenizer can influence value of each metric)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- etc

---

- [x] #222
- [x] #223

**Comment by vkehfdl1** [comment]
How can get and write option about metrics at yaml file? It can be tricky, but if it is necessary, we'll find a way.

**Comment by vkehfdl1** [comment]
close this issue because all generation metric has options. 
DONE!
