### ISSUE TITLE
bm25_path .\resources\bm25_gpt2.pkl does not exist. Please ingest first.

### ISSUE THREAD

**Issue by maglore9900** [Marker-Inc-Korea/AutoRAG#576]
ran through the tutorial using the simple_openai.yaml and it worked. I am trying to use the full.yaml and I am getting the following error

`bm25_path .\resources\bm25_gpt2.pkl does not exist. Please ingest first.`

I checked the resources folder and it does not in fact have the bm25_gpt2.pkl 
![image](https://github.com/user-attachments/assets/4973735a-4c9c-4c60-8846-feac2536be7d)

![image](https://github.com/user-attachments/assets/98db556d-ae00-4d52-a280-26fbcec8f9d6)

I have looked for resources in the github to manually download, but have not found any.

Any help on this error is greatly appreciated.

**Comment by vkehfdl1** [comment]
Hello @maglore9900 
You must create new project directory and specify it when run the evaluation.

use `--project_dir` parameter at cli. Or use `project_dir` parameter when run the trial(evaluation)

**Comment by maglore9900** [comment]
Appreciate the quick feedback. I am using the python script you provided, which you can see below

`

from autorag.evaluator import Evaluator
from dotenv import load_dotenv

load_dotenv()
evaluator = Evaluator(qa_data_path='corpus/qa.parquet', corpus_data_path='corpus/corpus.parquet')
evaluator.start_trial('full.yaml')
`

it failed when running the full.yaml, so I restarted it with 
`

from autorag.evaluator import Evaluator
from dotenv import load_dotenv

load_dotenv()

evaluator = Evaluator(qa_data_path='corpus/qa.parquet', corpus_data_path='corpus/corpus.parquet')
evaluator.restart_trial(trial_path='3')`

and that results in the error provided above. 

so, where would the --project_dir go?

**Comment by maglore9900** [comment]
if that is the suggestion, it still failed in the same way.

![image](https://github.com/user-attachments/assets/8ef11153-fac1-4add-b615-ae7fa79ebe17)


![image](https://github.com/user-attachments/assets/687513bd-cad4-4239-bfdc-6d88f3096d6e)

**Comment by vkehfdl1** [comment]
I think you need to make a **new directory** as new project directory. And set it to the `project_dir` parameter. Can you try that again?

**Comment by maglore9900** [comment]
The issue is that the current code was not recognizing the bm25_porter_stemmer.pkl, even though its supposed to. The solution on my side was basically a hack where I commented out the detection code in the module and explicitly put in bm25_porter_stemmer.pkl. 

I was running autorag with python 3.10 on windows 11 from within visual studio code.

Hope that information allows you to correct the issue.

**Comment by vkehfdl1** [comment]
Thanks @maglore9900 
It can be a Windows issue.
We'll look into this issue thanks.

**Comment by vkehfdl1** [comment]
It looks okay at mac.
