### ISSUE TITLE
안녕하세요 AutoRAG 테스트 중 Connection오류 생겨서 질문드립니다.

### ISSUE THREAD

**Issue by dongju923** [Marker-Inc-Korea/AutoRAG#578]
안녕하세요 현재 AutoRAG 0.2.10 버전을 사용중입니다.
![image](https://github.com/user-attachments/assets/b987b8b6-e983-4f53-bedf-d6b1a5aaf5fe)

현재 중간에 워닝이 한번 뜨고 이후에 에러가 찍히는데

![image](https://github.com/user-attachments/assets/a78fc89d-4cbd-4fa4-93fc-95479b4c0d79)

header가 잘못되었다고 오류가 뜹니다. 혹시 어떻게 해결해야 할까요??ㅠㅠ

config.yaml 은 compat_openai 사용중이고, 데이터는 load_eli5_dataset.py 로 실행해서 사용중입니다.,

ps. 0.2.10 버전에서 autorag/evaluation/metric/generation.py 에서 belu함수의 타입 힌트가 잘못된 거 같습니다.
![image](https://github.com/user-attachments/assets/0f020db7-2992-42a2-a373-eafa26aff7a5)

**Comment by dongju923** [comment]
해결: .env 말고 export 로 api_key를 지정하면 동작한다!

**Comment by vkehfdl1** [comment]
답을 찾으셨네요! 
.env를 사용하려면 파이썬 파일에서 따로 load_dotenv()를 해주셔야 합니다^^
