### ISSUE TITLE
Failed to send a request to an API server deployed with AutoRAG

### ISSUE THREAD

**Issue by rjwharry** [Marker-Inc-Korea/AutoRAG#615]
I got an error when sending request to my api server.
## Reproduce
1. Deploy API Server
```python
from autorag.deploy import Runner

runner = Runner.from_yaml("./pipeline.yaml")
runner.run_api_server()
```
2. Send Request
```bash
curl -X POST "http://localhost:8000/run" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"query\":\"my question\"}"
```
3. Error
```bash
results = loop.run_until_complete(process_batch(tasks, batch_size=batch))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 518, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.
```
## Environment
OS: Ubuntu 20.04
python: 3.11.9
AutoRAG: 0.2.13

**Comment by rjwharry** [comment]
Even I upgrade my AutoRAG with `pip install AutoRAG --upgrade`, I got an error.  
It seems already fixed this error, but I cannot get fixed version.

**Comment by vkehfdl1** [comment]
Hello, this bug fixed at #611 
But did not released at pypi yet.
You can install current main branch through pip like this.

```bash
pip install git+https://github.com/Marker-Inc-Korea/AutoRAG.git
```

Also, the new version will release soon in this week.

**Comment by vkehfdl1** [comment]
@rjwharry It will fix your error. If you couldn't,  let me know.

**Comment by rjwharry** [comment]
I tested it on my local and it worked! Thank you for your answer.

**Comment by vkehfdl1** [comment]
@rjwharry That sounds great! Thanks~
