### ISSUE TITLE
[Feature Request] Add new logo

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG#623]
**Is your feature request related to a problem? Please describe.**
Now, the AutoRAG logo image generated by Dall-e 2 of OpenAI. It has no meaning, lame, not good, not catchy at all. No sense of design. It is bad. 

**Describe the solution you'd like**
Some designer or who can write great midjourney prompt can help us. 

**Additional context**
Someday we can make sticker of AutoRAG? For your macbook 👍

**Comment by skmanzg** [comment]
Am I the only one who can not find the current AutoRAG logo? I cannot find it anywhere lol. btw, I might try this via FLUX but, could you specify the logo design you have imagined? You may require specifically like... the logo should be ~~~   with reference images attached if possible. Even if I am not the one who does that eventually, these specified requirements can be really helpful for possible future volunteer contributors or may be requested by them with high possibility. Note that using FLUX costs some money personally so it may take time. This is why I said 'I might try' instead of 'I will do it for you', being clear confirmation.

**Comment by vkehfdl1** [comment]
![image](https://github.com/user-attachments/assets/db76bc89-0ba8-416d-89b3-fda475795613)

@skmanzg 
This is current AutoRAG logo. 
Since it is not good, we don’t use it very often.

**Comment by vkehfdl1** [comment]
@skmanzg Plus thank you for your kind reply for this issue (+ instreset as well)

I think the logo should be simple and show the name of the product is “AutoRAG” 
Actually I like logo of Tensorflow, intuitive just have T & F.
It doesn’t need to be fancy. 
I prefer OBS or pytorch ones. 
But since we are “AutoRAG”, and the name has nothing to do with some kind of object. 
So I don’t know what to choose. 
(Like LlamaIndex have “Llama” and Langchain have “chain” that easily make their logo to llama or chain)


Actually, **ideation itself needs many help** from community. We are quite bad at thinking about design stuffs 😭

**Comment by vkehfdl1** [comment]
We find our logo LOL :) 
![image](https://github.com/user-attachments/assets/0dcc7952-4a46-415d-8659-7313c08ced7d)

**Comment by skmanzg** [comment]
@vkehfdl1 you remind me of this thing when I was working on my things. These are neither professional results nor creations from FLUX but I have tried. You can use or refer to those results if they are ok.
![스크린샷 2024-09-25 103310](https://github.com/user-attachments/assets/7a3b9d39-055b-44d5-83e5-b95f37716d3c)

![스크린샷 2024-09-25 103521](https://github.com/user-attachments/assets/95a3c23b-511c-4e49-b605-a49aea91fd9b)
![스크린샷 2024-09-25 103627](https://github.com/user-attachments/assets/f40a478d-1a2b-4be3-9a71-e5b730232f40)
![스크린샷 2024-09-25 103646](https://github.com/user-attachments/assets/50aa3bee-46d3-4941-ad0d-5d0f8b303698)
![스크린샷 2024-09-25 103627 2](https://github.com/user-attachments/assets/5397b914-6308-4d8a-8a97-9c7169b75ff9)
![스크린샷 2024-09-25 103646 - 복사본](https://github.com/user-attachments/assets/7885036a-03e1-4710-b526-2396502f0ee5)

**Comment by skmanzg** [comment]
@vkehfdl1  you might consider those too.

![스크린샷 2024-09-25 103627 2 - 복사본2](https://github.com/user-attachments/assets/2bb9ccd4-aff7-4699-b052-a3dc7253494a)
![스크린샷 2024-09-25 103627 2 - 복사본3](https://github.com/user-attachments/assets/bd957559-d76b-4dae-865d-c2baca2af561)

**Comment by skmanzg** [comment]
@vkehfdl1   More two::

![스크린샷 2024-09-25 103646 - 복사본 - 복사본 - 복사본](https://github.com/user-attachments/assets/5c7eccd0-6d58-4a53-bcc6-f8597bd70073)
![스크린샷 2024-09-25 103646 - 복사본 - 복사본](https://github.com/user-attachments/assets/d1aa729c-acf2-47bb-adfc-49eb76da4621)

**Comment by vkehfdl1** [comment]
@bwook00 Check this out!!

**Comment by vkehfdl1** [comment]
@skmanzg Added first one at AutoRAG linkedIn page
https://www.linkedin.com/company/autorag/?viewAsMember=true

**Comment by vkehfdl1** [comment]
Plan to change discord server logo as well....

**Comment by vkehfdl1** [comment]
Thank you for contribution and support! 
@taehallm suggest a new logo for AutoRAG.
![Image](https://github.com/user-attachments/assets/33d2a072-1cc6-48ad-aefb-a554a5b401b5)

The below is now official AutoRAG logo!!! 

Closing this issue since we have logo

**Comment by taehallm** [comment]
I now am an official contributor 😂
