### ISSUE TITLE
[trivial issue] typo in the document

### ISSUE THREAD

**Issue by skmanzg** [Marker-Inc-Korea/AutoRAG#631]
> > @vkehfdl1 
> > There is another very trivial typo in https://docs.auto-rag.com/data_creation/tutorial.html.
> > 
> > it says `# It have to contain 'query' and 'generation_gt' columns.` but `it has to contain` instead of `it have to contain...` ...
> > Idk. tbh, it is very remarkable typo to me. 😅
> > 
> 
> 
> 
> 
> 
> 
> _Originally posted by @skmanzg in https://github.com/Marker-Inc-Korea/AutoRAG/issues/629#issuecomment-2301198157_

            
I thought it was too trivial so I left the comment in the other's PR but I made a issue by the request from @vkehfdl1 .
Since I have no right to fix the typo in the document (ofc!), I leave the issue here only.

**Comment by vkehfdl1** [comment]
@skmanzg Thanks 👍
