### ISSUE TITLE
[Feature Request] Add Dockerfile for running AutoRAG

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG#671]
**Is your feature request related to a problem? Please describe.**
Because of the parsing modules, it is become much harder to install everything right in the environment.
Especially, because of the `pySSL`, `poppler-utils`, and `tesseract-ocr`. 
It looks much better to use different container to work on it smoothly. 

**Describe the solution you'd like**
- Write a Dockerfile for this.
- **MUST RUN WHOLE TEST IN THE DOCKERFILE**
- Use Docker image at github actions also. In this scenario, we have to find out how automatically build, how deploy to github registry, and pull it to test actions. => This better be extra issue.

**Describe alternatives you've considered**
Maybe make .sh file for installation. But we have virtual env actually.

**Comment by vkehfdl1** [comment]
Possible deploy to the ECS

**Comment by vkehfdl1** [comment]
@hongsw will assign this issue

**Comment by hongsw** [comment]
https://github.com/Marker-Inc-Korea/AutoRAG/pull/763
