### ISSUE TITLE
[BUG] Does it work in a multi-GPU environment?

### ISSUE THREAD

**Issue by daegonYu** [Marker-Inc-Korea/AutoRAG#691]
**Describe the bug**
When I try to infer llm locally, only the 0th GPU is used. Is there a guide to using multi GPU?

**Comment by vkehfdl1** [comment]
@daegonYu 
Hello.
We do not have multi-GPU environment yet, so we couldn't experiment multi-GPU environment yet.

**Comment by vkehfdl1** [comment]
@daegonYu 
Hi
Fortunately we get multi-gpu server and investigating this issue

**Comment by daegonYu** [comment]
Okay, thank you.

**Comment by vkehfdl1** [comment]
Not resolve this issue yet
