### ISSUE TITLE
[Feature Request] Can you add azure open ai implementation for autoRAG?

### ISSUE THREAD

**Issue by wanjeakshay** [Marker-Inc-Korea/AutoRAG#714]
I want to add azure open ai credentials for embedding and llm model for performing AutoRAG.

Current embedding only support openai credentials.

and if possible add documentation for Azure Open AI, quick start

**Comment by vkehfdl1** [comment]
@wanjeakshay 
Hello you can use azure openai and embedding with llama_index in AutoRAG.

Here is the documentation how to implement it.
https://docs.auto-rag.com/local_model.html

If you are in trouble to do it, please ask me again (mention please)

**Comment by wanjeakshay** [comment]
Hi @vkehfdl1, thank you for the doc link, I updated my code to include azure AI embedding like this

from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding
import autorag
from autorag import LazyInit

# You need to deploy your own embedding model as well as your own chat completion model
embed_model = AzureOpenAIEmbedding(
    model=my_embed_model,
    deployment_name=,
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

autorag.embedding_models['azureAI'] = LazyInit(AzureOpenAIEmbedding, model_name="text-embedding-ada-002")

also updated my config file
node_lines:
- node_line_name: retrieve_node_line
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_precision]
      top_k: 3
      modules:
        - module_type: vectordb
          embedding_model: azureAI
        - module_type: bm25
        - module_type: hybrid_rrf
          target_modules: ('bm25', 'vectordb')
          rrf_k: [5, 10, 30]
          
          
while executing following block of code
from langchain_community.callbacks import get_openai_callback

with get_openai_callback() as cb:
  evaluator.start_trial('/content/config.yaml')

print(f"Total Tokens: {cb.total_tokens}")
print(f"Completion Tokens: {cb.completion_tokens}")
print(f"Total Cost (USD): ${cb.total_cost}")

getting error:
WARNING:llama_index.embeddings.openai.utils:Retrying llama_index.embeddings.openai.base.get_embeddings in 0.14871869129193727 seconds as it raised APIConnectionError: Connection error..
WARNING:llama_index.embeddings.openai.utils:Retrying llama_index.embeddings.openai.base.get_embeddings in 0.8552518927105286 seconds as it raised APIConnectionError: Connection error..
WARNING:llama_index.embeddings.openai.utils:Retrying llama_index.embeddings.openai.base.get_embeddings in 2.653576097114074 seconds as it raised APIConnectionError: Connection error..

all my configurations are correct I have cross checked


also how can I add multiple models in it for testing which model is suitable, can we customely give chunk size and all??

**Comment by vkehfdl1** [comment]
@wanjeakshay 
Hello, it looks like you missed the api key and azure_endpoint at the embedding model. 

```python
import os
import autorag

autorag.embedding_models['azureAI'] = LazyInit(AzureOpenAIEmbedding, model_name="text-embedding-ada-002”,
api_key=os.getenv(“AZURE_API_KEY”), azure_endpoint=os.getenv(“AZURE_OPENAI_ENDPOINT"))
```

And you need to set the `AZURE_API_KEY` and `AZURE_OPENAI_ENDPOINT` env variable properly.

Or, it looks like you can set `OPENAI_API_KEY` env variable as api key and `AZURE_OPENAI_ENDPOINT` env varaible as azure endpoint in the llama index. You can try this also.

**Comment by vkehfdl1** [comment]
Since it looks you managed, and works well in the AutoRAG, closing this issue.

**Comment by hellangleZ** [comment]
> [@wanjeakshay](https://github.com/wanjeakshay) Hello you can use azure openai and embedding with llama_index in AutoRAG.
> 
> Here is the documentation how to implement it. https://docs.auto-rag.com/local_model.html
> 
> If you are in trouble to do it, please ask me again (mention please)

Hi @vkehfdl1 I read the document which folder files I need change the configuration to support Azure OPENAI

Because there is too much python file。。

Thanks

**Comment by vkehfdl1** [comment]
@hellangleZ 
You don’t need to change AutoRAG python file for azure OpenAI
All you need to do is add one line for adding generator_model, and run it as python code, not in cli.
Please read the instructions again and follow it.

**Comment by vkehfdl1** [comment]
@hellangleZ Can you check your api key or endpoint? It looks like the api key has some error.

**Comment by hellangleZ** [comment]
> [@hellangleZ](https://github.com/hellangleZ) Can you check your api key or endpoint? It looks like the api key has some error.

Hi  @vkehfdl1  I check my api key is could work, is there something wrong in my code ?

Could you please help to check?

Thanks

This is my configure.yaml

node_lines:

node_line_name: retrieve_node_line # Arbitrary node line name
nodes:
node_type: retrieval
strategy:
metrics: [retrieval_f1, retrieval_recall, retrieval_precision]
top_k: 3
modules:
module_type: vectordb
vectordb: default
embedding_model: azureAI1
node_line_name: post_retrieve_node_line # Arbitrary node line name
nodes:
node_type: prompt_maker
strategy:
metrics: [bleu, meteor, rouge]
modules:
module_type: fstring
prompt: "Read the passages and answer the given question. \n Question: {query} \n Passage: {retrieved_contents} \n Answer : "
node_type: generator
strategy:
metrics: [bleu, rouge]
modules:
module_type: llama_index_llm
llm: azureAI2
This is my code:

import os
from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding
import autorag
from autorag import LazyInit
from autorag.evaluator import Evaluator

os.environ["AZURE_OPENAI_API_KEY"] = "*****************************"
os.environ["AZURE_OPENAI_ENDPOINT"] = "https://a-wxf.openai.azure.com/"

autorag.embedding_models['azureAI1'] = LazyInit(
AzureOpenAIEmbedding,
model_name="text-embedding-3-small",
api_key=os.getenv("AZURE_OPENAI_API_KEY"),
azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
deployment_name="ada3",
api_version="2023-05-15",
)

autorag.generator_models['azureAI2'] = LazyInit(
AzureOpenAI,
model_name="gpt-4o",
api_key=os.getenv("AZURE_OPENAI_API_KEY"),
azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
deployment_name="gpt-4o",
api_version="2024-08-01-preview",
)

evaluator = Evaluator(qa_data_path='/aml/project_auto_rag/qa_train.parquet',
corpus_data_path='/aml/project_auto_rag/corpus.parquet',
project_dir='/aml/project_auto_rag')
evaluator.start_trial('/aml/project_auto_rag/config.yaml')

**Comment by hellangleZ** [comment]
Hi  @wanjeakshay  Is you resolve the problem or not, if you do , could you please share your code ?

Thanks

**Comment by hellangleZ** [comment]
![Image](https://github.com/user-attachments/assets/0d401045-4345-4ab5-8962-d1d996c98a32)
 I  confirm it is not a api key issue, after I check with llama_index common rag， it works good by the api

**Comment by qinqinqaq** [comment]
same question
