### ISSUE TITLE
[BUG]  windows Installation is difficult on Windows. Can you make it easier to use on Windows as well?

### ISSUE THREAD

**Issue by Yoontaewoong** [Marker-Inc-Korea/AutoRAG#786]
Installation is difficult on Windows. Can you make it easier to use on Windows as well?

**Comment by Yoontaewoong** [comment]
Building wheel for chroma-hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for chroma-hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      creating build\temp.win-amd64-cpython-312\Release\python_bindings
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\user\AppData\Local\Temp\pip-build-env-o56aopuq\overlay\Lib\site-packages\pybind11\include -IC:\Users\user\AppData\Local\Temp\pip-build-env-o56aopuq\overlay\Lib\site-packages\numpy\_core\include -I./hnswlib/ -IC:\Users\user\.conda\envs\auto_rag\include -IC:\Users\user\.conda\envs\auto_rag\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0" /EHsc /Tp./python_bindings/bindings.cpp /Fobuild\temp.win-amd64-cpython-312\Release\./python_bindings/bindings.obj /EHsc /openmp /O2 /DVERSION_INFO=\\\"0.7.6\\\"
      bindings.cpp
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\cfloat(10): fatal error C1083: 포함 파일을 열 수 없습니다. 'float.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chroma-hnswlib
Failed to build chroma-hnswlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (chroma-hnswlib)

**Comment by vkehfdl1** [comment]
Close this issue because of inactivity. 
Windows users! Recommend to use Docker container.
