### ISSUE TITLE
[Feature Request] docker image push CI/CD

### ISSUE THREAD

**Issue by hongsw** [Marker-Inc-Korea/AutoRAG#806]
**Is your feature request related to a problem? Please describe.**
The current process of manually building and pushing Docker images is time-consuming and prone to errors. It's particularly challenging to maintain consistency when managing multiple environments or versions.

**Describe the solution you'd like**
We need an automated CI/CD pipeline using GitHub Actions to automatically build Docker images and push them to Docker Hub. This pipeline should trigger whenever code changes are merged into the main branch.
Describe alternatives you've considered

**Describe alternatives you've considered**
Setting up a CI/CD pipeline using Jenkins
Using GitLab CI/CD (which would require migrating from GitHub to GitLab)
Creating semi-automated deployment scripts

**Additional context**
https://hub.docker.com/repository/docker/autoraghq/autorag/general

docker pull autoraghq/autorag:0.3.3-all
docker pull autoraghq/autorag:0.3.3-ko
docker pull autoraghq/autorag:0.3.3-parse
docker pull autoraghq/autorag:0.3.3-dev

'all' includes all features, 'ko' adds Korean support, 'parse' is a lightweight version with parsing only, and 'dev' is the latest development version with potential instabilities.

**Comment by alexkreidler** [comment]
This is awesome!

Could we add something that pushes the `autorag-frontend` image too? Also, it would be nice if the `docker-compose.yml` used the pushed images by default so we don't run into issues like #1102 from being on the bleeding edge. 

Maybe we can add a separate `docker-compose.dev.yml` that builds from local Dockerfiles? Or name the other `docker-compose.prod.yml` that pins to stable Docker Hub images and direct users in the README to use that one.
