### ISSUE TITLE
[BUG] pip install -U AutoRAG fails: Cannot uninstall distutils-installed blinker 1.4

### ISSUE THREAD

**Issue by abdshomad** [Marker-Inc-Korea/AutoRAG#886]
![Image](https://github.com/user-attachments/assets/c67e56e6-4886-4d45-aeec-287dfcbd3934)

**Comment by abdshomad** [comment]
**Describe the bug**

Environment: Google Colab running AutoRAG Tutorial 2 - Evaluation Dataset Creation.ipynb

`pip` fails to install -Uq AutoRAG[parse]>=0.3.0 datasets. It required to uninstall the `blinker` package (version 1.4) when attempting to upgrade `AutoRAG`, preventing the upgrade process from completing. The error message indicates that `blinker` was installed using `distutils`, making it difficult for `pip` to identify all associated files for removal.

**To Reproduce**

1. Run the following command in a terminal or console:  `pip install -Uq AutoRAG[parse]>=0.3.0 datasets`
2. Observe the error message.


**Expected behavior**

`pip` should successfully uninstall the older version of `blinker` and then install/upgrade `AutoRAG` and its dependencies without error.


**Full Error log**

```
error: uninstall-distutils-installed-package
× Cannot uninstall blinker 1.4
└> It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```


**Code that bug is happened**

The bug occurs when executing the following command:

```python
# In a terminal or console
pip install -Uq AutoRAG[parse]>=0.3.0 datasets 
```

**Additional context**

* The root cause appears to be the use of the deprecated `distutils` installation method for the `blinker` package.  `pip` has improved its handling of packages over time, but it still struggles with cleanly uninstalling packages installed via `distutils`.  
* Manually removing `blinker` might be a workaround, but it's not recommended due to the risk of accidentally deleting files belonging to other packages.  A more robust solution within `pip` itself is desirable.
![Image](https://github.com/user-attachments/assets/0f58658d-74cb-480e-a590-ce0c83fb3077)

**Comment by vkehfdl1** [comment]
@abdshomad Hello!
Try this before installing AutoRAG in colab.

```
%pip install blinker==1.4 ipykernel==5.5.6
```

**Comment by abdshomad** [comment]
> [@abdshomad](https://github.com/abdshomad) Hello! Try this before installing AutoRAG in colab.
> 
> ```
> %pip install blinker==1.4 ipykernel==5.5.6
> ```

I tried but still failed. Here's the screenshot. NOTE: I am running it in Google Colab link provided in this repo. 

![Image](https://github.com/user-attachments/assets/5d2f5d08-008d-477b-928b-3acc10c3a11a)

Any other option I can try?

**Comment by vkehfdl1** [comment]
@abdshomad 
We are working on this issue on the #888 PR...

**Comment by vkehfdl1** [comment]
@abdshomad 

```
%%shell
apt-get remove python3-blinker
pip install blinker==1.8.2
%pip install -Uq ipykernel==5.5.6 ipywidgets-bokeh==1.0.2
```

Use this on the colab before installing AutoRAG

We updated colab tutorial!
