### ISSUE TITLE
[Feature Request] Add custom_query_gen function

### ISSUE THREAD

**Issue by rjwharry** [Marker-Inc-Korea/AutoRAG#892]
**Is your feature request related to a problem? Please describe.**
Different LLM models result in different prompts, especially for local LLMs. Why not allow users to try their own queries?

**Describe the solution you'd like**
Implement custom_query_gen function receiving user's custom query generation prompt.

**Comment by rjwharry** [comment]
If you think it is good, please assign to me

**Comment by bwook00** [comment]
@rjwharry 
Thanks for making this issue!
I think this feature will make it easier to create synthetic queries.

I just assigned it!
