### ISSUE TITLE
[Feature Request] Add CLI Version Check

### ISSUE THREAD

**Issue by hongsw** [Marker-Inc-Korea/AutoRAG#910]
**Is your feature request related to a problem? Please describe.**
It’s difficult to verify the CLI version quickly, leading to compatibility issues.

**Describe the solution you'd like**
Add a version check command (e.g., --version or -v) to display the current CLI version.

**Describe alternatives you've considered**
Manually checking version details in files.
/python3.10/site-packages/AutoRAG-0.3.8.dist-info/

or 
```sh 
$ pip show autorag
Name: AutoRAG
Version: 0.3.8
...
```
**Additional context**
N/A

**Comment by vkehfdl1** [comment]
@hongsw 
You can check `VERSION` file.

```python
with open(‘VERSION’, ‘w’) as f:
    version = f.read()
```

Something like this?

**Comment by hongsw** [comment]
$ autorag -V

AutoRAG v0.3.8

Here's what I expect it to do
