### ISSUE TITLE
[BUG] Kkma raises UnicodeDecodeError when text includes emoji

### ISSUE THREAD

**Issue by rjwharry** [Marker-Inc-Korea/AutoRAG#930]
**Describe the bug**
When emoji is included in text, Kkma raises `UnicodeDecodeError` in `morphs(text)` function.

**To Reproduce**
1. Use `ko_kkma` as tokenizer in retrieval node
2. Include text with emoji in corpus.parquet
3. Run validator

**Expected behavior**
Pass validation

**Full Error log**
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte`

**Desktop (please complete the following information):**
 - OS: Linux
 - Python version 3.10

**Comment by rjwharry** [comment]
Maybe removing emoji is one of the solution

**Comment by rjwharry** [comment]
Please assign to me, I'll figure it out

**Comment by vkehfdl1** [comment]
@rjwharry I assigned to you, but it is possible that this error is not occured because of ko_kkma.
I think it will be possible that `normalize_unicode` function occured the error in the `utils/util.py`
