### ISSUE TITLE
[BUG] The vectordb setting is always applied as default when validating

### ISSUE THREAD

**Issue by rjwharry** [Marker-Inc-Korea/AutoRAG#942]
**Describe the bug**
Event I configure vectordb, always set as default when validating

**To Reproduce**
1. Configure yaml with custom vectordb configuration
2. Run validation
3. See error

**Expected behavior**
Ingest vectordb with my configuration

**Full Error log**
not error

**Code that bug is happened**
`config_dict` is full dict of config.yaml, so it only has **node_lines** as key. 
vectordb_list always becomes empty list because `config_dict` has to "vectordb" key.  
If that's not what you intended, it need to be fixed it.
```python
def load_all_vectordb_from_yaml(
    yaml_path: str, project_dir: str
) -> List[BaseVectorStore]:
    config_dict = load_yaml_config(yaml_path)
    vectordb_list = config_dict.get("vectordb", [])
    if len(vectordb_list) == 0:
        chroma_path = os.path.join(project_dir, "resources", "chroma")
        return [
            load_vectordb(
                "chroma",
                client_type="persistent",
                embedding_model="openai",
                collection_name="openai",
                path=chroma_path,
            )
        ]
...
```
**Suggestion**
We need to ingest vectordb configured in retrieval node

**Comment by rjwharry** [comment]
I'll get vectordb configuration from retrieval node

**Comment by rjwharry** [comment]
Or maybe ingest all vectordb in config.yaml like bm25 did

**Comment by rjwharry** [comment]
I need to be fixed right now! This is not only for validation but also Evaluator.
I think we should ingest all vectordb in config.yaml like bm25

**Comment by vkehfdl1** [comment]
@rjwharry Can you provide your config YAML file?
I will check it also.

**Comment by vkehfdl1** [comment]
@rjwharry 
Actually I think it is intended. We changed the VectorDB configuration setting since v0.3.8

https://docs.auto-rag.com/integration/vectordb/vectordb.html
Here is the full documentation how to set different vectorDB, also embedding models.

You must configure the vectorDB at the `vectordb` key and use it on the retrieval `vectordb` module.

**Comment by rjwharry** [comment]
I've figured out how to configure VectorDB. This is my mistake, let me close this issue
