### ISSUE TITLE
🐛 Fix WORK_DIR path resolution in development environment (api/)

### ISSUE THREAD

**Issue by hongsw** [Marker-Inc-Korea/AutoRAG#969]
**Describe the bug**

https://github.com/Marker-Inc-Korea/AutoRAG/blob/81a2f63e26f1ed7c4d292c340f4a82fa216a6263/api/app.py#L91

**To Reproduce**

**Expected behavior**

**Full Error log**
If applicable, add full error log to help explain your problem.

**Code that bug is happened**
If applicable, add the code that bug is happened.
(Especially, your AutoRAG YAML file or python codes that you wrote)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, MacOS]
 - Python version [e.g. 3.10]

**Additional context**

**Comment by vkehfdl1** [comment]
I am on it!

**Comment by vkehfdl1** [comment]
close at #971 and #968
