### ISSUE TITLE
[API] Add endpoint for env variable management

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG#974]
GET /env => return all env variable key

DELETE /env/<string:key> => delete the certain key as a env variable.

We will manage with '.env' file comes with app.py file. 
Load it when the api-key needed endpoint starting. (parse, chunk, qa creation, validation, evaluate, chat)

**Comment by hongsw** [comment]
Is It work with .env.local file?

**Comment by vkehfdl1** [comment]
@hongsw It works with `.env` file at the api folder. API key only for running AutoRAG.

**Comment by vkehfdl1** [comment]
close at #975
