### ISSUE TITLE
[API] fix validate and evaluation api config, set_trial_config

### ISSUE THREAD

**Issue by hongsw** [Marker-Inc-Korea/AutoRAG#984]
https://github.com/Auto-RAG/autorag-frontend/issues/3

`/projects/<string:project_id>/trials/<string:trial_id>/validate`
`/projects/<string:project_id>/trials/<string:trial_id>/evaluate`

Issue
Managing nested data with CSVs is inefficient, and frequent dumps are cumbersome.

Solution
Switch to SQLite with asynchronous execution managed by Celery for safe task handling.

Plan
Test project creation, trials (1, 2, 3), validation, and execution in the new setup.

**Comment by hongsw** [comment]
draft

**Comment by vkehfdl1** [comment]
close at #1016
