### ISSUE TITLE
[API] The filepath configuration schema needs to be updated from (raw_data, parse, chunk, qa) to (files, knowledges, qa_docs).

### ISSUE THREAD

**Issue by hongsw** [Marker-Inc-Korea/AutoRAG#996]
- [x] Celery integration completed.  
- [x] SQLiteProjectDB migration completed.  
- [x] `trial_task.py` is to be determined (TBD); assistance needed from @vkehfdl1.  
- [x] Frontend migration completed, including changes to the `waitForTask` function.
- [ ] The filepath configuration schema needs to be updated from `(raw_data, parse, chunk, qa)` to `(files, knowledges, qa_docs)`.
<img width="842" alt="image" src="https://github.com/user-attachments/assets/1c96f6f1-0d05-45fb-ab98-cd126e8dc9db">
Figure 1: Files are initially managed in the files folder. In the knowledges folder, selected files are processed, parsed, and chunked for further use. QA documents are generated and stored in the qa_docs folder. Lastly, in the trials folder, specific knowledge and QA documents are selected to perform evaluations and generate reports.

_Originally posted by @hongsw in https://github.com/Marker-Inc-Korea/AutoRAG/issues/987#issuecomment-2496144117_

**Comment by vkehfdl1** [comment]
close at #1011
